package pl.poznan.put.cs.si.puttalky
 
import pl.poznan.put.cs.si.puttalky.Fakt;
import pl.poznan.put.cs.si.puttalky.Zamowienie; 
import pl.poznan.put.cs.si.puttalky.Ciasto;
import pl.poznan.put.cs.si.puttalky.Dodatek;
import pl.poznan.put.cs.si.puttalky.BazaWiedzy;
import java.util.Set;

import org.semanticweb.HermiT.Reasoner;
import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLClassExpression;
import org.semanticweb.owlapi.model.OWLObjectProperty;
import org.semanticweb.owlapi.model.OWLOntology;
import org.semanticweb.owlapi.model.OWLOntologyCreationException;
import org.semanticweb.owlapi.model.OWLOntologyManager;
import org.semanticweb.owlapi.reasoner.OWLReasoner;
import java.util.List;


/** Author: agalawrynowicz<br>
 * Date: 19-Dec-2016 */

rule "start"
	salience 3
	
	when
		not Fakt(nazwa=="start")
		zamowienie : Zamowienie()
	then
		zamowienie.powitanie();
		System.out.println();
		System.out.println();
		insert(new Fakt("start", "0"));
end

rule "Podaj dodatki"
	salience 2
	
	when
		not Fakt(nazwa == "dodatek")
		dodatek : Dodatek()
		parser : Parser()
		baza : BazaWiedzy()
	then
		  dodatek.setMonit("Jaki dodatek powinna zawieraÄ‡ Twoja pizza?:\n");
		  dodatek.zadajPytanie();
		  parser.przetworzOdpowiedz();
		 
		for (String slowo : parser.getSlowaKluczowe()){
			for (String uriKlasy : baza.dopasujDodatek(slowo)) { 
		        insert(new Fakt("dodatek", uriKlasy));
		    } 
		}
		    		
		//@TODO	brak dopasowania
		
		update(dodatek);
end

rule "Podaj rodzaj ciasta"
	salience 2
	
	when
		not Fakt(nazwa == "rodzaj_ciasta")
		ciasto : Ciasto()
		parser : Parser()
	then
		  ciasto.setMonit("Podaj rodzaj ciasta:\n");
		  ciasto.zadajPytanie();
		  parser.przetworzOdpowiedz();
		 
		for (String slowo : parser.getSlowaKluczowe()){
			if (slowo.equals("cienki")){
		       insert(new Fakt("rodzaj_ciasta", "cienkie"));
			} else if (slowo.equals("gruby")) {
		       insert(new Fakt("rodzaj_ciasta", "grube"));
			}
		}
					
		//@TODO	brak dopasowania
		
		update(ciasto);
end

rule "Polecana pizza"
	salience 1
	
	when
		Fakt(nazwa == "dodatek") && 
		Fakt(nazwa == "rodzaj_ciasta") && 	
		not Fakt(nazwa == "pizza_propozycja") &&
        $dodatek : Fakt( nazwa == "dodatek")
 		
		baza: BazaWiedzy()
		pizza: Pizza()
	then

		Set<String> pizze = baza.wyszukajPizzePoDodatkach($dodatek.getWartosc());
            
        if (pizze.size()>1){            		
			for (String nazwaPizzy : pizze) {
				insert(new Fakt("pizza_propozycja", nazwaPizzy));
		    	//System.out.println();
		    	if (!nazwaPizzy.equals("Nothing")){
		       	   System.out.println("Polecam pizzÄ™:"+nazwaPizzy);
		       	}
		    }
		}
		else {
			System.out.print("Przygotujemy pizzÄ™Â specjalnÄ…Â z dodatkami: ");
			System.out.println($dodatek.getWartosc().split("#")[1]);
	    	insert(new Fakt("pizza_propozycja", "Specjalna pizza"));
	    }
end


rule "wybór pizzy"
	when
		not (Fakt(nazwa == "wybor")) &&
		Fakt(nazwa == "pizza_propozycja") 
		pizza : Pizza() 
		parser : Parser() 
		baza: BazaWiedzy()
//		zamowienie: Zamowienie()
	then
		pizza.setMonit("Podaj zamawianą pizzę:\n");
		pizza.zadajPytanie();
		parser.przetworzOdpowiedz();
		
		for (String slowo : parser.getSlowaKluczowe()){
			for (String uriKlasy : baza.dopasujPizze(slowo)) { 
				insert(new Fakt("wybor", "0"));
		    	break;
        	} 
		}
	//	update(zamowienie)
end

rule "zakoÅ„czenie"

	when
		not (Fakt(nazwa == "koniec")) &&
		Fakt(nazwa == "wybor") &&
		zamowienie : Zamowienie()
	then
		insert(new Fakt("koniec", "0"));
		zamowienie.pozegnanie();
end

